version: "3.9"
services: 
  app:
    container_name: react-vsbai
    image: react-vsbai:latest
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./build:/home/www-data/build